name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  prebuild:
    name: Test on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-15-intel]
        node-version: [20.x, 22.x, 24.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build native tests
        run: npm run build

      - name: Run native tests
        run: npm run test

      - name: Prebuild
        shell: bash
        run: npm run prebuild

      - name: Upload prebuilds
        uses: actions/upload-artifact@v4
        with:
          name: ref-napi-prebuild-${{ matrix.os }}-${{ matrix.node-version }}
          path: prebuilds/

  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: [prebuild]
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Download all prebuilds
        uses: actions/download-artifact@v5
        with:
          path: prebuilds
      - run: ls -R prebuilds/

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
